CXX = g++
CXXFLAGS = -Wall -Werror -Wextra -pedantic -std=c++17
LDFLAGS = -Wno-deprecated-declarations -std=c++17
LBLIBS = 

OS := $(shell uname)
ifeq ($(OS),Darwin)
	LBLIBS += -framework OpenGL -framework GLUT -framework Cocoa 
else
	LBLIBS += -lGL -lGLU -lglut
endif

LIBSFOLDER = library

SRC = *.cpp
OBJ = $(SRC:.cc=.o)
EXEC = run.app

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CXX) $(LDFLAGS) -o $@ $(OBJ) $(LBLIBS) $(LIBSFOLDER)/*.cpp

clean:
	rm -rf *.o $(EXEC)

run: all
	./$(EXEC) arena_3.svg